### ISSUE TITLE
Unable to delete photos from a post after uploading

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1615] opened 2024-04-10 17:29 UTC
Hi all, I've run into an issue deleting uploaded photos on Hylo. I'm using the web app in chrome / Arc browser.

I uploaded multiple photos, though couldn't delete them using the "x" at the top right of the image. I posted a post and went back in to edit it and was still unable to delete the photos. Attaching a screen recording. 

Uploading Screen Recording 2024-04-10 at 11.23.25 AM.mov…

**Comment by KevinTriplett** [comment] 2024-04-10 18:51
Hi Krisha, I'm able to replicate this in my development environment, I'll see if I can find the bug.

**Comment by KrishaTerranIO** [comment] 2024-04-11 00:45
Thanks Kevin!

**Comment by KevinTriplett** [comment] 2024-04-11 12:00
So far, I've confirmed this was not caused by the recent commits to allow duplication of posts: with the dev branch from 2 weeks ago I also can't delete images from a post.

**Comment by KevinTriplett** [comment] 2024-04-11 12:43
Found the bug -- when clicking on 'X' the system thinks you are wanting to drag and re-order images. I'll work on finding a way to exclude the 'X' icon from the draggable elements.

**Comment by KevinTriplett** [comment] 2024-04-11 13:29
Opened issue #1616 so closing this one.

**Closed by KevinTriplett** 2024-04-11 13:29 UTC
